---
- name: Create node-exporter base directory
  ansible.builtin.file:
    path: "{{ node_exporter_base_dir }}"
    state: directory
    mode: '0755'

- name: Deploy node-exporter docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ node_exporter_base_dir }}/docker-compose.yml"
    mode: '0644'

- name: Start node-exporter
  community.docker.docker_compose_v2:
    project_src: "{{ node_exporter_base_dir }}"
    state: present
    recreate: always
    remove_orphans: true
