apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.smb.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    username: {{ .Values.smb.encryptedUsername | quote }}
    password: {{ .Values.smb.encryptedPassword | quote }}
  template:
    metadata:
      name: {{ .Values.smb.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
