{
 "title": "Argo Workflows — CI/CD",
 "description": "Metrics from Argo Workflows compatible with multi-Prometheus origins like Thanos.",
 "tags": [ "argo" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dc",
    "label": "Kubernetes Cluster",
    "query": {
     "query": "label_values(argo_workflows_count,prometheus)"
    }
   },
   {
    "name": "ns",
    "label": "WF Controller Namespace",
    "query": {
     "query": "label_values(argo_workflows_count{prometheus=~\"^$dc$\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Currently",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"background-color:white; height:100%\">\n<img src=\"https://user-images.githubusercontent.com/25306803/43103633-a5d61dc4-8e83-11e8-9f0e-7ccdbee01eb6.png\" />\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "WF Pending",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argo_workflows_count{prometheus=~\"^$dc$\",namespace=~\"$ns\",status=\"Pending\"})"
    }
   ]
  },
  {
   "title": "WF Running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argo_workflows_count{prometheus=~\"^$dc$\",namespace=~\"$ns\",status=\"Running\"})"
    }
   ]
  },
  {
   "title": "WF Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argo_workflows_count{prometheus=~\"^$dc$\",namespace=~\"$ns\",status=\"Error\"})"
    }
   ]
  },
  {
   "title": "WF Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argo_workflows_count{prometheus=~\"^$dc$\",namespace=~\"$ns\",status=\"Failed\"})"
    }
   ]
  },
  {
   "title": "WF Skipped",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{prometheus=~\"^$dc$\",namespace=~\"$ns\",status=\"Skipped\"}"
    }
   ]
  },
  {
   "title": "WF Succeeded",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argo_workflows_count{prometheus=~\"^$dc$\",namespace=~\"$ns\",status=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Number of Workflows currently accessible by the Controller by status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Workflow Status  ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (prometheus, namespace, status) (argo_workflows_count{status!~\"(Error|Failed)\",namespace=~\"$ns\",prometheus=~\"^$dc$\"})",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{status}}"
    }
   ]
  },
  {
   "title": "Workflow Errors/Failures ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (prometheus, namespace, status) (argo_workflows_count{status=~\"(Error|Failed)\",namespace=~\"$ns\",prometheus=~\"^$dc$\"})",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{status}}"
    }
   ]
  },
  {
   "title": "Histogram of durations of operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Workflow operation duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(argo_workflows_operation_duration_seconds_bucket{prometheus=~\"^$dc$\",namespace=~\"^$ns$\"}[5m])) by (le,prometheus,namespace)) ",
     "legendFormat": "{{prometheus}} : {{namespace}} : 95th "
    }
   ]
  },
  {
   "title": "Adds to the queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Workflow queue adds ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (prometheus, namespace, queue_name) (increase(argo_workflows_queue_adds_count{prometheus=~\"^$dc$\",namespace=~\"$ns\"}[2m]))",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{queue_name}}"
    }
   ]
  },
  {
   "title": "Depth of the queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (prometheus, namespace, queue_name) (argo_workflows_queue_depth_count{prometheus=~\"^$dc$\",namespace=~\"$ns\"})",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{queue_name}}"
    }
   ]
  },
  {
   "title": "Time objects spend waiting in the queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  rate(argo_workflows_queue_latency_sum{queue_name=\"cron_wf_queue\",namespace=~\"^$ns$\",prometheus=~\"^$dc$\"}[1m])\n/\n  rate(argo_workflows_queue_latency_count{queue_name=\"cron_wf_queue\",namespace=~\"^$ns$\",prometheus=~\"^$dc$\"}[1m])",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{queue_name}}"
    },
    {
     "expr": "  rate(argo_workflows_queue_latency_sum{queue_name=\"pod_queue\",namespace=~\"^$ns$\",prometheus=~\"^$dc$\"}[1m])\n/\n  rate(argo_workflows_queue_latency_count{queue_name=\"pod_queue\",namespace=~\"^$ns$\",prometheus=~\"^$dc$\"}[1m])",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{queue_name}}"
    },
    {
     "expr": "  rate(argo_workflows_queue_latency_sum{queue_name=\"wf_cron_queue\",namespace=~\"^$ns$\",prometheus=~\"^$dc$\"}[1m])\n/\n  rate(argo_workflows_queue_latency_count{queue_name=\"wf_cron_queue\",namespace=~\"^$ns$\",prometheus=~\"^$dc$\"}[1m])",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{queue_name}}"
    },
    {
     "expr": "  rate(argo_workflows_queue_latency_sum{queue_name=\"workflow_queue\",namespace=~\"^$ns$\",prometheus=~\"^$dc$\"}[1m])\n/\n  rate(argo_workflows_queue_latency_count{queue_name=\"workflow_queue\",namespace=~\"^$ns$\",prometheus=~\"^$dc$\"}[1m])",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{queue_name}}"
    }
   ]
  },
  { "title": "Total number of Workflow Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Workflow Pods by State",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (prometheus, namespace, status) (argo_workflows_pods_count{prometheus=~\"^$dc$\",namespace=~\"$ns\"})",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{status}}"
    }
   ]
  },
  {
   "title": "Total number of log messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Log messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (prometheus, namespace, level) (rate(log_messages{namespace=~\"$ns\",prometheus=~\"^$dc$\"}[1m]))",
     "legendFormat": "{{prometheus}} : {{namespace}} : {{level}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "options": {
    "content": "---\n\n[![Pipekit Logo](https://helm.pipekit.io/assets/pipekit-logo.png)](https://pipekit.io?utm_campaign=grafana-dashboard)\n\nPipekit is the control plane for Argo Workflows. Platform teams use Pipekit to manage data & CI pipelines at scale, while giving developers self-serve access to Argo. Pipekit's unified logging view, enterprise-grade RBAC, and multi-cluster management capabilities lower maintenance costs for platform teams while delivering a superior devex for Argo users.\n\nFor help with Argo Workflows metrics, and overall Argo support, contact the Pipekit team at [hello@pipekit.io](mailto:hello@pipekit.io)."
   }
  }
 ]
}