---
# Handlers for paperless
- name: Restart paperless compose
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ paperless_base_dir }}"
    files:
      - "{{ paperless_compose_file }}"
    state: restarted
    pull: always
