---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gameserver-scheduler
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gameserver-scheduler
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["kubevirt.io"]
    resources: ["virtualmachines"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gameserver-scheduler
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: gameserver-scheduler
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: gameserver-scheduler
  apiGroup: rbac.authorization.k8s.io
