{{- if .Values.sealedSecret.encryptedUserdata -}}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedSecret.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gameserver
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  encryptedData:
    userdata: {{ .Values.sealedSecret.encryptedUserdata | quote }}
  template:
    metadata:
      name: {{ .Values.sealedSecret.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
