---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gameserver-ui
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gameserver-ui
                port: { number: 80 }
