{{- if and .Values.sealedSecret.encryptedSessionSecret .Values.sealedSecret.encryptedAdminPassword -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedSecret.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    sessionSecret: {{ .Values.sealedSecret.encryptedSessionSecret | quote }}
    adminPassword: {{ .Values.sealedSecret.encryptedAdminPassword | quote }}
  template:
    metadata:
      name: {{ .Values.sealedSecret.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
