{{- if .Values.sshSecret.encryptedPrivateKey }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sshSecret.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    privateKey: {{ .Values.sshSecret.encryptedPrivateKey | quote }}
    {{- if .Values.sshSecret.encryptedPublicKey }}
    publicKey: {{ .Values.sshSecret.encryptedPublicKey | quote }}
    {{- end }}
  template:
    metadata:
      name: {{ .Values.sshSecret.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
