{{- if and .Values.telnet.secretName .Values.telnet.encryptedPassword }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.telnet.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    password: {{ .Values.telnet.encryptedPassword | quote }}
  template:
    metadata:
      name: {{ .Values.telnet.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
