---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  labels:
    {{- include "media.labels" "prowlarr" | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.config.storageClass }}
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    {{- include "media.labels" "prowlarr" | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr
  template:
    metadata:
      labels:
        {{- include "media.labels" "prowlarr" | nindent 8 }}
    spec:
      containers:
        - name: prowlarr
          image: {{ .Values.images.prowlarr }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          env:
            {{- include "media.lsioEnv" (dict "theme" "prowlarr" "root" $) | nindent 12 }}
          ports:
            - name: http
              containerPort: 9696
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources.arr | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config
---
{{ include "media.svcIngress" (dict "name" "prowlarr" "port" 9696 "root" $) }}
