{{- if .Values.haMcpSecret.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.haMcpSecret.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ha-mcp.labels" . | nindent 4 }}
spec:
  encryptedData:
    token: {{ .Values.haMcpSecret.encryptedToken | quote }}
    secret-path: {{ .Values.haMcpSecret.encryptedSecretPath | quote }}
  template:
    metadata:
      name: {{ .Values.haMcpSecret.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
