---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: "AgBQZAant5dkxKgJN/E7zAVra53lHc9tgS0gCN/fS3XXxxMKnvGv2MVhvydrIfaaW4z/TyRKoFGKQlngq8wUxQw6tE2Jj5YLdskVXyGrsZ48bvbDGIhvXHvnjFkWrLpL6/5A23WpLOgAvoB5goaeqAeNo+EYx8y1YCfqt7uFwUcsrtXD0e0cqstAFUX1uxv9RwFh/6+TOBguS1Y/EAhRpNRgkCD3GwuSLX8gPDv73liAJ0WDIyQyZK9JSOfz+JBgLEj362S4rswWArQbpIMA380GLVADVXTTTx/+LtbzEkWNdchacqTX44xZ6htBQFhNHFOKOpFBAKShhB7idhHGkh/6SkMJYu29CCgaNDlsV+FyAosN60gi4ByrUKW3VunSBYIo6R4UD5OXopAkSffJKgcB4TefruTZO7wI5rH0RtHjZPX9Ae5OxOmpRO0ofz0ItNzOHOyNUi6/w8m2MtikwNr1IksjUMxolzPn2ZnASQI/EJUB1PM826W0JwDkr2ibXtOnwFcivDpilzimu7A4tSyT4z5AAz83cINu4aiy1e0ZldQf5aGJ5VaJx0Uj3dowu4xWbXcsqmjU5SpeNLgm1ugGpIponvdIssNeNs1GBpVcWJnqFGUQsSr2RQG0nWOYcYb7c2mGkos8bsorA+X9ComewRYsf+jDEVhOI5+SRKyUb6AEb8NK5d9NzO5BbYYp7ZHEhlYPNtHmNyiRJNPuHveT42UsjEoJApey4uNc2pyv"
    admin-user: "AgBZoj5cyoxm7qAbDH4htCFZ3U8Rzcp471N4yhkr7sJ6uNhqd2270J8HDlyFGatcgVtDp7MWMCYfpnm8EUvpe8nteHqK+ZYtOXt3NEBMtIL8XDXA2P1bbuqvYhPNz+v8zVATBhDmQUmVEMxTi4gDiklDyGmFvKBRLMOdarkc373NU/TUmbToW/X2n0eIAzc7rZvXu0NeMU8zJZBzi5NpVAP0H0wcP9LDICFLCoW7CO7qGwAZolYa6XcuffqMCHkd86EAcM5AIdyU+vLIn1k05bupB769MXwuaz+l4SpOucuF9+2plTwVYElwx0W6lNIqweL5wzb6dBJfsPIUnZqHTJmzxztXAKxOgsTz2vJJLWlxsoU2g54autf5H7udYVcBVbcMxn477ajKM7zZG0fn14NHYSIIPSqEIi5YXU3MfoyIqjb0ExK9qaUjzsQ7chgMK+g2qmGwEtMeyCqRHx3DcJECK9bLLYHd0OVdZEUe41BT0J0NWKsjW9Yw7DkrzakCQgAPft0qz+gnhEldmRGt1Vv9moKU94oPFngGxUNrIJWjq61HcG7vnpkJKCV71d5nBeDQ78/5f3hpkhd4Kl4TpZQUDRkC+5gARqTsq8UfHN2HJGDzYV0z48m3vQaYt5oQK4qHsvwwyFgeYNlal6gTdJa6TQBOIF0qHWEAS2FRKqOAKRxWLnvBLzC0xe5JRljTprL9vOiqQ=="
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
