---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: "AgBQZAant5dkxKgJN/E7zAVra53lHc9tgS0gCN/fS3XXxxMKnvGv2MVhvydrIfaaW4z/TyRKoFGKQlngq8wUxQw6tE2Jj5YLdskVXyGrsZ48bvbDGIhvXHvnjFkWrLpL6/5A23WpLOgAvoB5goaeqAeNo+EYx8y1YCfqt7uFwUcsrtXD0e0cqstAFUX1uxv9RwFh/6+TOBguS1Y/EAhRpNRgkCD3GwuSLX8gPDv73liAJ0WDIyQyZK9JSOfz+JBgLEj362S4rswWArQbpIMA380GLVADVXTTTx/+LtbzEkWNdchacqTX44xZ6htBQFhNHFOKOpFBAKShhB7idhHGkh/6SkMJYu29CCgaNDlsV+FyAosN60gi4ByrUKW3VunSBYIo6R4UD5OXopAkSffJKgcB4TefruTZO7wI5rH0RtHjZPX9Ae5OxOmpRO0ofz0ItNzOHOyNUi6/w8m2MtikwNr1IksjUMxolzPn2ZnASQI/EJUB1PM826W0JwDkr2ibXtOnwFcivDpilzimu7A4tSyT4z5AAz83cINu4aiy1e0ZldQf5aGJ5VaJx0Uj3dowu4xWbXcsqmjU5SpeNLgm1ugGpIponvdIssNeNs1GBpVcWJnqFGUQsSr2RQG0nWOYcYb7c2mGkos8bsorA+X9ComewRYsf+jDEVhOI5+SRKyUb6AEb8NK5d9NzO5BbYYp7ZHEhlYPNtHmNyiRJNPuHveT42UsjEoJApey4uNc2pyv"
    admin-user: "AgCEs3ChGtRwMV4ydMudqC/UJHrofvGAO4FMjT/5hXPdfdS6rTRNOe+G0Mj4Yb1SlYJJgDEWS1U1LNAKkc+3saKNjRW68pP9/h7nfeOXlu5hD6Y5zLJchANhFLRr7MAlAuzUSsuv2gfbNJkT4oxSrVIPqdRs27WQ1Cz7UvsmrUWi4uFUoLDuXLTxVO86WItmP6LeVnVcutuZCyicZSvjTDHw1TbKmphfaMV3J3hYNK0oeWhmm3dJrXe5n4ZhurDZaq7foGCBm9m4LfSfjOZVNhPzzULnlzXtU0x12/LrjlMl9B+izgCSetTYTkVpbq1fEwcjQASAMTYTiLfj7FVQEKys+livtQIkxSV2+Ee33mAZo8ek29qpZ9FSBe5sSGcO2Ai1CkkSwfI7VBm1xEiQ2nY8KEZbiJ8CzxFDgMikdswoFstA/cY4veZn4M5mi57y1wVStOrEKJaz2vMgAS77zwbteyzUI4TC2Z48nzkHYhUr650WJD6TvIP/fZM+g2Gj8xkNTYDHr+TU2zA5fHx7+apge6mow/hhisIXmiXCquDxktOVJuHE9Di4PPrgbWtz1KHaCVKTfq4zm7yVM1JRB3LooID0Ewnt1TskU7CniNoS2nM8j7I4MAKRbWSHG+df8ldpJGe5mciYnHgO3NP/Av5mlGiXBQMGocA/aUVISqiFuYdFpqT/GyGB4TF6l29nyVQPzuN8lw=="
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
