apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: argocd
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/part-of: argocd
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
