apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: pihole-exporter
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - pihole
  selector:
    matchLabels:
      app: pihole-exporter
  endpoints:
    - port: metrics
      path: /metrics
