apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: argo-workflows
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - argo-workflows
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-workflows-server
  endpoints:
    - port: "2746"
      path: /metrics
