{{- if and .Values.sealedSecret.encryptedUsername .Values.sealedSecret.encryptedPassword -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedSecret.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  encryptedData:
    username: {{ .Values.sealedSecret.encryptedUsername | quote }}
    password: {{ .Values.sealedSecret.encryptedPassword | quote }}
  template:
    metadata:
      name: {{ .Values.sealedSecret.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
