{{- if .Values.auth.encryptedPasswordFile -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.auth.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  encryptedData:
    passwd: {{ .Values.auth.encryptedPasswordFile | quote }}
  template:
    metadata:
      name: {{ .Values.auth.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
